version: "2"
services:
  requisition-ui:
    image: openlmis/dev-ui:7.0.0
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
    depends_on:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
  auth-ui:
    image: openlmis/auth-ui:6.1.0
    volumes:
      - '/openlmis-auth-ui'
  fulfillment-ui:
    image: openlmis/fulfillment-ui:6.0.0
    volumes:
      - '/openlmis-fulfillment-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.3.0
    volumes:
      - '/openlmis-referencedata-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:1.1.0
    volumes:
     - '/openlmis-stockmanagement-ui'
  ui-components:
    image: openlmis/ui-components:5.3.1-SNAPSHOT
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.1.0
    volumes:
      - '/openlmis-ui-layout'
  image:
    build: .
    image: openlmis/requisition-ui
